// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type LongReminder struct {
	Id             string
	Title          string
	IntervalDays   int64
	UserId         int64
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
	LastRemindedAt sql.NullTime
	MarkedDoneAt   sql.NullTime
	IsEnabled      bool
}

type Project struct {
	Id        int64
	UserId    sql.NullInt64
	Title     string
	Slug      string
	Notes     string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type RefreshToken struct {
	Id        int64
	UserId    sql.NullInt64
	Jwt       string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type User struct {
	Id        int64
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Version struct {
	Number    int64
	AppliedAt time.Time
}
