// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type DailyBrevoSend struct {
	Id        int64
	Number    int64
	Date      string
	CreatedAt string
	UpdatedAt string
}

type GuestLoginToken struct {
	Token     string
	Email     string
	CreatedAt string
}

type LongReminder struct {
	Id             string
	Title          string
	IntervalDays   int64
	UserId         int64
	CreatedAt      string
	UpdatedAt      sql.NullString
	LastRemindedAt sql.NullString
	MarkedDoneAt   sql.NullString
	IsEnabled      bool
}

type Project struct {
	Id        int64
	UserId    sql.NullInt64
	Title     string
	Slug      string
	Notes     string
	CreatedAt string
	UpdatedAt sql.NullString
	SortIndex int64
}

type RefreshToken struct {
	Id        int64
	UserId    sql.NullInt64
	Jwt       string
	ExpiresAt string
	CreatedAt string
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type User struct {
	Id        int64
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt sql.NullString
	IsGuest   bool
}

type Version struct {
	Number    int64
	AppliedAt string
}
